# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20170513_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
